#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# File: semaphore
#
# This file is part of Semaphore
#
# Copyright (C) 2014 Evaldo Junior <evaldojuniorbento@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Lesser GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the Lesser GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.


from getopt import getopt
from os import getcwd, system
from sys import argv, exit
from Tkinter import Tk


def help():
    print u"""Usage: semaphore -c "command" [-t seconds]"""


def parse_params():
    try:
        args = getopt(argv[1:], "c:t:")
    except Exception, e:
        print e
        help()
        exit(1)

    command = ""
    time = 5

    for opt, arg in args[0]:
        if opt == "-c":
            command = arg
        elif opt == "-t":
            time = int(arg)

    if command == "":
        help()
        exit(1)

    return command, time


def run(window, time, command):
    if int(system(command)) == 0:
        window.configure(background="green")
    else:
        window.configure(background="red")
    window.after(time, run, window, time, command)


def main():
    command, time = parse_params()
    cwd = getcwd()
    title = command
    command = "cd %s; %s > /dev/null 2>&1" % (cwd, command)
    time = time * 1000

    window = Tk()
    window.title("Running %s" % (title))
    run(window, time, command)
    window.mainloop()


if __name__ == "__main__":
    main()
